const cardDataList = [
  {
    id: 1,
    playerName: "Zet",
    discord:
      "https://www.youtube.com/watch?v=dQw4w9WgXcQ&ab_channel=RickAstley",
    twitch: "",
    twitter: "",
    bigtime: "",
    imageSrc: "/images/assets/dao.png",
    infoContent:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit... Lorem ipsum dolor sit amet consectetur adipisicing elit... Lorem ipsum dolor sit amet consectetur adipisicing elit... Lorem ipsum dolor sit amet consectetur adipisicing elit... Lorem ipsum dolor sit amet consectetur adipisicing elit...",
    bigTimeContent: "Je suis le contenu de la page Bigtime pour Zet",
    gameContent: "Lorem ipsum dolor sit amet consectetur adipisicing elit...",
    passionContent: "J'adore mes stagiaires wouhou",
  },
  {
    id: 2,
    playerName: "Istaranga",
    discord:
      "https://www.youtube.com/watch?v=dQw4w9WgXcQ&ab_channel=RickAstley",
    twitch: "",
    twitter: "",
    bigtime: "",
    imageSrc: "/images/hero.webp",
    infoContent: "Lorem ipsum dolor sit amet consectetur adipisicing elit...",
    bigTimeContent: "Je suis le contenu de la page Bigtime pour Istaranga",
    gameContent: "Lorem ipsum dolor sit amet consectetur adipisicing elit...",
    passionContent: "J'adore The Hackin Project",
  },
  {
    id: 3,
    playerName: "Omiage",
    discord:
      "https://www.youtube.com/watch?v=dQw4w9WgXcQ&ab_channel=RickAstley",
    twitch: "",
    twitter: "",
    bigtime: "",
    imageSrc: "/images/assets/dao.png",
    infoContent: "Lorem ipsum dolor sit amet consectetur adipisicing elit...",
    bigTimeContent: "Je suis le contenu de la page Bigtime pour Omiage",
    gameContent: "Lorem ipsum dolor sit amet consectetur adipisicing elit...",
    passionContent: "J'adore photoshop OMG",
  },
  {
    id: 4,
    playerName: "Olivier",
    discord:
      "https://www.youtube.com/watch?v=dQw4w9WgXcQ&ab_channel=RickAstley",
    twitch: "",
    twitter: "",
    bigtime: "",
    imageSrc: "/images/assets/dao.png",
    infoContent: "Lorem ipsum dolor sit amet consectetur adipisicing elit...",
    bigTimeContent: "Je suis le contenu de la page Bigtime pour Olivier",
    gameContent: "Lorem ipsum dolor sit amet consectetur adipisicing elit...",
    passionContent: "J'adore le CSS wow !",
  },
  {
    id: 4,
    playerName: "Karine",
    discord:
      "https://www.youtube.com/watch?v=dQw4w9WgXcQ&ab_channel=RickAstley",
    twitch: "",
    twitter: "",
    bigtime: "",
    imageSrc: "/images/assets/dao.png",
    infoContent: "Lorem ipsum dolor sit amet consectetur adipisicing elit...",
    bigTimeContent: "Je suis le contenu de la page Bigtime pour Karine",
    gameContent: "Lorem ipsum dolor sit amet consectetur adipisicing elit...",
    passionContent: "Les chats et les chats",
  },
  {
    id: 5,
    playerName: "",
    discord: "",
    twitch: "",
    twitter: "",
    bigtime: "",
    imageSrc: "",
    infoContent: "",
    bigTimeContent: "",
    gameContent: "",
    passionContent: "",
  },
];

export default cardDataList;
